version: '2'

services:

  redcap-webapp:
    build: .
    container_name: redcap
    depends_on:
      - redcap-db
    ports:
      - 80:80

  redcap-db:
    image: mariadb
    container_name: redcap-db
    volumes:
      - redcap-db-data:/var/lib/mysql
    env_file:
      - local.conf

volumes:
  redcap-db-data:
    driver: local
